services:
  gq-gateway:
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    ports:
      - 3000:8080
    environment:
      FRONTEND_URL: http://gq-playground:3000/
      DOCS_URL: http://gq-docs:8080/
      API_URL: http://gq-server:3000/
    depends_on:
      - gq-playground
      - gq-docs
      - gq-server
  gq-playground:
    build:
      context: .
      dockerfile: docker/playground.Dockerfile
  gq-docs:
    build:
      context: .
      dockerfile: docker/docs.Dockerfile
    environment:
      BASE_PATH: /docs
  gq-server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/db
    depends_on:
      - db
  db:
    image: docker.io/postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
