[package]
name = "gq-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.4.0"
gq-core = { path = "../core" }
pretty_env_logger = "0.5.0"
serde_json = "1.0.116"
