import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Montserrat } from "next/font/google";
import { Toaster } from "sonner";
const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(
          "min-h-screen font-sans antialiased",
          montserrat.variable
        )}
      >
        <Toaster
          offset={"16px"}
          toastOptions={{
            unstyled: true,
            classNames: {
              toast:
                "w-full flex gap-4 bg-background items-center border border-accent p-4 rounded-md shadow-md",
              title: "text-foreground text-sm",
              actionButton:
                "min-w-max bg-foreground text-background text-xs px-2 py-1 rounded-md justify-self-end",
            },
          }}
        />
        <div>{children}</div>
      </body>
    </html>
  );
}
