[package]
name = "gq-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json.workspace = true
log.workspace = true
derive-getters = "0.4.0"
once_cell = "1.19.0"
uuid = { version = "1.8.0", features = ["v4"] }
gq-core = { path = "../core" }
