set dotenv-load

# https://github.com/launchbadge/sqlx/blob/main/sqlx-cli/README.md
# The DATABASE_URL env var must be set to run those commands
# If there is a .env file located at `crates/server/.env`, it will be loaded automatically
sqlx-prepare-check:
    cargo sqlx prepare --check --workspace
sqlx-prepare: # To be able to build the project without database
    cargo sqlx prepare --workspace
sqlx-migrate:
    cargo sqlx migrate run
