# This workflow runs whenever a PR is opened or updated, or a commit is pushed to main. It runs
# several checks:
# - check: checks that the code does not contain any biome warnings

# This configuration allows maintainers of this repo to create a branch and pull request based on
# the new branch. Restricting the push trigger to the main branch ensures that the PR only gets
# built once.
on:
  push:
    branches: [main]
  pull_request:
# If new code is pushed to a PR branch, then cancel in progress workflows for that PR. Ensures that
# we don't waste CI time, and returns results quicker https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: nextjs
jobs:
  ci:
    runs-on: ubuntu-latest
    name: biome ci
    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
        with:
          working-dir: crates/web/frontend
      - name: Run biome check
        working-directory: crates/web/frontend
        run: biome --version
